### ISSUE TITLE
align-deps: pnpm catalogs

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#3221]
pnpm introduced catalogs feature in [9.5.0](https://github.com/pnpm/pnpm/releases/tag/v9.5.0).

Yarn v4.10 also [supports catalogs](https://yarnpkg.com/features/catalogs).

### Bare minimum support

- [x] Ignore `catalog:` protocol (we are already protocol agnostic)
    - [ ] https://github.com/microsoft/rnx-kit/pull/3817

### Great to support

- [x] Add command to export catalogs: https://github.com/microsoft/rnx-kit/pull/3812
    - [ ] Support `--presets`: https://github.com/microsoft/rnx-kit/pull/3815
- [ ] Should `align-deps` verify catalogs defined in `pnpm-workspace.yaml`?
    ```yaml
    # Default catalogs
    catalog:
      chalk: ^4.1.2

    # Named catalogs
    catalogs:
      react16:
        react: ^16.7.0
        react-dom: ^16.7.0
      react17:
        react: ^17.10.0
        react-dom: ^17.10.0
    ```
